name: openAI
configs_agents:
- class_string: boardgames.agents.openai_agent:OpenAI_Agent
  model: gpt-4o-mini
- class_string: boardgames.agents.openai_agent:OpenAI_Agent
  model: gpt-4o-mini
- class_string: boardgames.agents.openai_agent:OpenAI_Agent
  model: gpt-4o-mini
- class_string: boardgames.agents.openai_agent:OpenAI_Agent
  model: gpt-4o-mini
- class_string: boardgames.agents.openai_agent:OpenAI_Agent
  model: gpt-4o-mini
- class_string: boardgames.agents.openai_agent:OpenAI_Agent
  model: gpt-4o-mini
- class_string: boardgames.agents.openai_agent:OpenAI_Agent
  model: gpt-4o-mini
- class_string: boardgames.agents.openai_agent:OpenAI_Agent
  model: gpt-4o-mini
- class_string: boardgames.agents.openai_agent:OpenAI_Agent
  model: gpt-4o-mini
- class_string: boardgames.agents.openai_agent:OpenAI_Agent
  model: gpt-4o-mini
- class_string: boardgames.agents.openai_agent:OpenAI_Agent
  model: gpt-4o-mini