name: random_and_human
configs_agents:
- class_string: boardgames.agents.random:RandomAgent
- class_string: boardgames.agents.random:RandomAgent
- class_string: boardgames.agents.random:RandomAgent
- class_string: boardgames.agents.random:RandomAgent
- class_string: boardgames.agents.human:HumanAgent