name: randoms
configs_agents:
- class_string: boardgames.agents.random:RandomAgent
- class_string: boardgames.agents.random:RandomAgent
- class_string: boardgames.agents.random:RandomAgent
- class_string: boardgames.agents.random:RandomAgent
- class_string: boardgames.agents.random:RandomAgent
