# Logging
do_wandb : False
wandb_config:
  project : Board Games with AI
do_tb : True
do_cli : True
do_tqdm : True



# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - game : ww
  - agents : rd
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .